import type { ThemeTokenBundle } from "@/lib/themeTokens"
import { normalizeThemeTokenBundle } from "@/lib/themeTokens"

export const FIXED_THEME_PRESET_IDS = [
  "ivory-ledger",
  "ease-health",
  "shadcn",
  "bmw",
  "modern-minimalist",
] as const

export const BASE_THEME_MODE = "base" as const
export type FixedThemePresetId = (typeof FIXED_THEME_PRESET_IDS)[number]
export type ThemeMode = typeof BASE_THEME_MODE | FixedThemePresetId | "custom"

type ThemePresetDefinition = {
  id: FixedThemePresetId
  label: string
  description: string
  preview: {
    background: string
    card: string
    primary: string
    accent: string
  }
  bundle: ThemeTokenBundle
}

const PRESET_SOURCE: Record<FixedThemePresetId, Omit<ThemePresetDefinition, "id" | "bundle"> & { tokens: ThemeTokenBundle }> = {
  "ivory-ledger": {
    label: "Ivory Ledger",
    description: "Warm paper, burgundy ink, editorial finance.",
    preview: {
      background: "#F4F1EA",
      card: "#FCFAF5",
      primary: "#6B2C39",
      accent: "#D4A85D",
    },
    tokens: {
      background: "#F4F1EA",
      foreground: "#2C2825",
      card: "#FCFAF5",
      "card-foreground": "#2C2825",
      popover: "#FCFAF5",
      "popover-foreground": "#2C2825",
      primary: "#6B2C39",
      "primary-foreground": "#FCFAF5",
      secondary: "#F3E8E9",
      "secondary-foreground": "#6B2C39",
      muted: "#E5E0D8",
      "muted-foreground": "#8C8477",
      accent: "#D4A85D",
      "accent-foreground": "#2C2825",
      border: "#E5E0D8",
      input: "#E5E0D8",
      ring: "#6B2C39",
    },
  },
  "ease-health": {
    label: "Ease Health",
    description: "Botanical wellness: forest ink, keylime wash, and cream paper serenity.",
    preview: {
      background: "#e1f4df",
      card: "#fffefc",
      primary: "#0f3e17",
      accent: "#b6ced5",
    },
    tokens: {
      background: "#e1f4df",
      foreground: "#222222",
      card: "#fffefc",
      "card-foreground": "#222222",
      popover: "#fffefc",
      "popover-foreground": "#222222",
      primary: "#0f3e17",
      "primary-foreground": "#fffefc",
      secondary: "#cfe7d3",
      "secondary-foreground": "#0f3e17",
      muted: "#b1dbb8",
      "muted-foreground": "#0c2f10",
      accent: "#b6ced5",
      "accent-foreground": "#222222",
      border: "#efeeeb",
      input: "#efeeeb",
      ring: "#0f3e17",
      radius: "14.08px",

      "bd-app-bg": "#fffefc",
      "bd-surface": "#fffefc",
      "bd-surface-muted": "#e1f4df",
      "bd-border": "#efeeeb",
      "bd-border-strong": "#0f3e17",
      "bd-text": "#222222",
      "bd-text-muted": "#0c2f10",
      "bd-text-soft": "#b1dbb8",
      "bd-input-bg": "#fffefc",
      "bd-input-border": "#efeeeb",
      "bd-input-focus": "#0f3e17",
      "bd-card-bg": "#fffefc",
      "bd-card-border": "#efeeeb",
      "bd-button-primary-bg": "#0f3e17",
      "bd-button-primary-text": "#fffefc",
      "bd-button-primary-hover-bg": "#0c2f10",
      "bd-nav-active-bg": "#e1f4df",
      "bd-nav-active-text": "#0f3e17",
      "bd-nav-active-icon": "#0f3e17",
      "bd-surface-action": "#fffefc",
      "bd-surface-action-hover": "#e1f4df",
      "bd-surface-action-border": "#efeeeb",
      "bd-surface-action-text": "#0f3e17",
      "bd-surface-action-muted": "#0c2f10",
      "bd-action-icon-bg": "#0f3e17",
      "bd-action-icon-text": "#fffefc",
      "bd-fab-bg": "#0f3e17",
      "bd-fab-text": "#fffefc",

      "bd-status-success-bg": "#e1f4df",
      "bd-status-success-text": "#0f3e17",
      "bd-status-success-border": "#b1dbb8",
      "bd-status-warning-bg": "#fdf6e3",
      "bd-status-warning-text": "#8a6d3b",
      "bd-status-warning-border": "#f0e0b0",
      "bd-status-danger-bg": "#fce4e4",
      "bd-status-danger-text": "#8b1a1a",
      "bd-status-danger-border": "#f0b0b0",
      "bd-status-info-bg": "#e1f4df",
      "bd-status-info-text": "#0f3e17",
      "bd-status-info-border": "#b1dbb8",

      "bd-radius-sm": "4px",
      "bd-radius-md": "7.04px",
      "bd-radius-lg": "14.08px",
      "bd-font-family": "'Suisse Intl', 'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-display-family": "'Faire Octave', 'Playfair Display', serif",
      "bd-font-h1-family": "'Faire Octave', 'Playfair Display', serif",
      "bd-font-label-family": "'Suisse Intl', 'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-body-size": "0.95rem",
      "bd-font-body-line-height": "1.5",
      "bd-font-display-size": "3.5rem",
      "bd-font-display-weight": "300",
      "bd-font-display-spacing": "-0.02em",
      "bd-font-h1-size": "2.5rem",
      "bd-font-h1-weight": "300",
      "bd-label-letter-spacing": "0.02em",

      "bd-space-sm": "14px",
      "bd-space-md": "28px",
      "bd-space-lg": "56px",
      "bd-card-padding": "28px",
      "bd-section-gap": "42px",
      "bd-row-gap": "14px",
      "bd-field-gap": "11px",
      "bd-sheet-padding": "28px",
    },
  },
  "shadcn": {
    label: "shadcn/ui",
    description: "Developer-tool neutrality: Geist type, near-black ink, red ember accent.",
    preview: {
      background: "#f5f5f5",
      card: "#ffffff",
      primary: "#0a0a0a",
      accent: "#e7000b",
    },
    tokens: {
      background: "#f5f5f5",
      foreground: "#0a0a0a",
      card: "#ffffff",
      "card-foreground": "#0a0a0a",
      popover: "#ffffff",
      "popover-foreground": "#0a0a0a",
      primary: "#171717",
      "primary-foreground": "#ffffff",
      secondary: "#f5f5f5",
      "secondary-foreground": "#171717",
      muted: "#f5f5f5",
      "muted-foreground": "#737373",
      accent: "#e7000b",
      "accent-foreground": "#ffffff",
      destructive: "#e7000b",
      "destructive-foreground": "#ffffff",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#171717",
      radius: "6px",

      "bd-app-bg": "#f5f5f5",
      "bd-surface": "#ffffff",
      "bd-surface-muted": "#f5f5f5",
      "bd-border": "#e5e5e5",
      "bd-border-strong": "#0a0a0a",
      "bd-text": "#0a0a0a",
      "bd-text-muted": "#737373",
      "bd-text-soft": "#a3a3a3",
      "bd-input-bg": "#ffffff",
      "bd-input-border": "#e5e5e5",
      "bd-input-focus": "#171717",
      "bd-card-bg": "#ffffff",
      "bd-card-border": "#e5e5e5",
      "bd-button-primary-bg": "#171717",
      "bd-button-primary-text": "#ffffff",
      "bd-button-primary-hover-bg": "#0a0a0a",
      "bd-nav-active-bg": "#f5f5f5",
      "bd-nav-active-text": "#0a0a0a",
      "bd-nav-active-icon": "#0a0a0a",
      "bd-surface-action": "#ffffff",
      "bd-surface-action-hover": "#f5f5f5",
      "bd-surface-action-border": "#e5e5e5",
      "bd-surface-action-text": "#0a0a0a",
      "bd-surface-action-muted": "#737373",
      "bd-action-icon-bg": "#0a0a0a",
      "bd-action-icon-text": "#ffffff",
      "bd-fab-bg": "#171717",
      "bd-fab-text": "#ffffff",

      "bd-status-success-bg": "#f0fdf4",
      "bd-status-success-text": "#166534",
      "bd-status-success-border": "#bbf7d0",
      "bd-status-warning-bg": "#fffbeb",
      "bd-status-warning-text": "#92400e",
      "bd-status-warning-border": "#fde68a",
      "bd-status-danger-bg": "#fef2f2",
      "bd-status-danger-text": "#991b1b",
      "bd-status-danger-border": "#fecaca",
      "bd-status-info-bg": "#eff6ff",
      "bd-status-info-text": "#1e40af",
      "bd-status-info-border": "#bfdbfe",

      "bd-radius-sm": "4px",
      "bd-radius-md": "6px",
      "bd-radius-lg": "10px",
      "bd-font-family": "Geist, ui-sans-serif, system-ui, sans-serif",
      "bd-font-display-family": "Geist, ui-sans-serif, system-ui, sans-serif",
      "bd-font-h1-family": "Geist, ui-sans-serif, system-ui, sans-serif",
      "bd-font-label-family": "Geist, ui-sans-serif, system-ui, sans-serif",
      "bd-font-body-size": "0.875rem",
      "bd-font-body-line-height": "1.5",
      "bd-font-display-size": "3rem",
      "bd-font-display-weight": "600",
      "bd-font-display-spacing": "-0.02em",
      "bd-font-h1-size": "2.25rem",
      "bd-font-h1-weight": "600",
      "bd-font-h1-spacing": "-0.02em",
      "bd-label-letter-spacing": "0.02em",

      "bd-space-sm": "12px",
      "bd-space-md": "20px",
      "bd-space-lg": "48px",
      "bd-card-padding": "24px",
      "bd-section-gap": "24px",
      "bd-row-gap": "12px",
      "bd-field-gap": "8px",
      "bd-sheet-padding": "24px",
    },
  },
  "bmw": {
    label: "BMW",
    description: "Automotive luxury: black finish with M-series blue.",
    preview: {
      background: "#000000",
      card: "#1C1C1C",
      primary: "#FFFFFF",
      accent: "#0066B3",
    },
    tokens: {
      background: "#000000",
      foreground: "#FFFFFF",
      card: "#1C1C1C",
      "card-foreground": "#FFFFFF",
      primary: "#FFFFFF",
      "primary-foreground": "#000000",
      secondary: "#000000",
      "secondary-foreground": "#A0A0A0",
      muted: "#1C1C1C",
      "muted-foreground": "#A0A0A0",
      accent: "#0066B3",
      "accent-foreground": "#FFFFFF",
      border: "#333333",
      input: "#333333",
      ring: "#0066B3",
      radius: "4px",
      "bd-app-bg": "#000000",
      "bd-surface": "#1C1C1C",
      "bd-surface-muted": "#111111",
      "bd-border": "#333333",
      "bd-border-strong": "#FFFFFF",
      "bd-text": "#FFFFFF",
      "bd-text-muted": "#A0A0A0",
      "bd-input-bg": "#1C1C1C",
      "bd-button-primary-bg": "#0066B3",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "2px",
      "bd-radius-md": "4px",
      "bd-radius-lg": "8px",
      "bd-font-family": "'Inter', sans-serif",
    },
  },
  "modern-minimalist": {
    label: "Modern Minimalist",
    description: "Clean grayscale palette for tech, architecture, and design.",
    preview: {
      background: "#F5F5F5",
      card: "#FFFFFF",
      primary: "#36454F",
      accent: "#708090",
    },
    tokens: {
      background: "#F5F5F5",
      foreground: "#36454F",
      card: "#FFFFFF",
      "card-foreground": "#36454F",
      popover: "#FFFFFF",
      "popover-foreground": "#36454F",
      primary: "#36454F",
      "primary-foreground": "#FFFFFF",
      secondary: "#D3D3D3",
      "secondary-foreground": "#36454F",
      muted: "#F0F0F0",
      "muted-foreground": "#708090",
      accent: "#708090",
      "accent-foreground": "#FFFFFF",
      border: "#D3D3D3",
      input: "#D3D3D3",
      ring: "#36454F",
      radius: "8px",

      "bd-app-bg": "#F5F5F5",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#F0F0F0",
      "bd-border": "#D3D3D3",
      "bd-border-strong": "#36454F",
      "bd-text": "#36454F",
      "bd-text-muted": "#708090",
      "bd-text-soft": "#94A3B8",
      "bd-input-bg": "#FFFFFF",
      "bd-input-border": "#D3D3D3",
      "bd-input-focus": "#36454F",
      "bd-card-bg": "#FFFFFF",
      "bd-card-border": "#D3D3D3",
      "bd-button-primary-bg": "#36454F",
      "bd-button-primary-text": "#FFFFFF",
      "bd-button-primary-hover-bg": "#2A363E",
      "bd-nav-active-bg": "#F0F0F0",
      "bd-nav-active-text": "#36454F",
      "bd-nav-active-icon": "#36454F",
      "bd-surface-action": "#FFFFFF",
      "bd-surface-action-hover": "#F5F5F5",
      "bd-surface-action-border": "#D3D3D3",
      "bd-surface-action-text": "#36454F",
      "bd-surface-action-muted": "#708090",
      "bd-action-icon-bg": "#36454F",
      "bd-action-icon-text": "#FFFFFF",
      "bd-fab-bg": "#36454F",
      "bd-fab-text": "#FFFFFF",

      "bd-status-success-bg": "#ECFDF5",
      "bd-status-success-text": "#065F46",
      "bd-status-success-border": "#A7F3D0",
      "bd-status-warning-bg": "#FFFBEB",
      "bd-status-warning-text": "#92400E",
      "bd-status-warning-border": "#FDE68A",
      "bd-status-danger-bg": "#FEF2F2",
      "bd-status-danger-text": "#991B1B",
      "bd-status-danger-border": "#FECACA",
      "bd-status-info-bg": "#F0F9FF",
      "bd-status-info-text": "#075985",
      "bd-status-info-border": "#BAE6FD",

      "bd-radius-sm": "4px",
      "bd-radius-md": "8px",
      "bd-radius-lg": "16px",
      "bd-font-family": "'Inter', sans-serif",
      "bd-font-display-family": "'Inter', sans-serif",
      "bd-font-h1-family": "'Inter', sans-serif",
      "bd-font-label-family": "'Inter', sans-serif",
      "bd-font-body-size": "0.9rem",
      "bd-font-body-line-height": "1.6",
      "bd-font-display-size": "3.5rem",
      "bd-font-display-weight": "300",
      "bd-font-display-spacing": "-0.03em",
      "bd-font-h1-size": "1.875rem",
      "bd-font-h1-weight": "500",
      "bd-font-label-weight": "600",
      "bd-label-letter-spacing": "0.1em",

      "bd-space-sm": "8px",
      "bd-space-md": "16px",
      "bd-space-lg": "32px",
      "bd-card-padding": "24px",
    },
  },
}

export const THEME_PRESETS: ThemePresetDefinition[] = FIXED_THEME_PRESET_IDS.map((id) => {
  const preset = PRESET_SOURCE[id]
  return {
    id,
    label: preset.label,
    description: preset.description,
    preview: preset.preview,
    bundle: normalizeThemeTokenBundle(preset.tokens, { allowRadius: true }),
  }
})

export function isFixedThemePresetId(value: unknown): value is FixedThemePresetId {
  return typeof value === "string" && FIXED_THEME_PRESET_IDS.includes(value as FixedThemePresetId)
}

export function getThemePreset(id: unknown): ThemePresetDefinition | null {
  if (!isFixedThemePresetId(id)) return null
  return THEME_PRESETS.find((preset) => preset.id === id) ?? null
}

export function resolveThemeMode(
  settings: {
    app_theme_preset_id?: unknown
    app_background_color?: unknown
    app_card_color?: unknown
    app_theme_tokens?: unknown
  } | null | undefined,
): ThemeMode {
  const presetId = settings?.app_theme_preset_id
  if (presetId === "custom" || isFixedThemePresetId(presetId)) return presetId

  // Backwards compatibility: explicit manual values should still behave as custom mode.
  if (settings?.app_background_color || settings?.app_card_color || settings?.app_theme_tokens) {
    return "custom"
  }

  return BASE_THEME_MODE
}
