import type { ThemeTokenBundle } from "@/lib/themeTokens"
import { normalizeThemeTokenBundle } from "@/lib/themeTokens"

export const FIXED_THEME_PRESET_IDS = [
  "ivory-ledger",
  "industrial-fog",
  "brutalist-concrete",
  "sage-retreat",
  "deep-onyx",
  "nordic-abyss",
  "obsidian",
  "emerald-vault",
  "ruby-ledger",
  "midnight-indigo",
  "scandi-pine",
  "swiss-grid",
  "notion-beige",
  "science-journal",
  "oss-terminal",
  "the-sun",
  "blackrock",
  "ramp",
  "binance",
  "uber",
  "bmw",
  "grand-budapest",
  "aqua-mint",
] as const

export const BASE_THEME_MODE = "base" as const
export type FixedThemePresetId = (typeof FIXED_THEME_PRESET_IDS)[number]
export type ThemeMode = typeof BASE_THEME_MODE | FixedThemePresetId | "custom"

type ThemePresetDefinition = {
  id: FixedThemePresetId
  label: string
  description: string
  preview: {
    background: string
    card: string
    primary: string
    accent: string
  }
  bundle: ThemeTokenBundle
}

const PRESET_SOURCE: Record<FixedThemePresetId, Omit<ThemePresetDefinition, "id" | "bundle"> & { tokens: ThemeTokenBundle }> = {
  "ivory-ledger": {
    label: "Ivory Ledger",
    description: "Warm paper, burgundy ink, editorial finance.",
    preview: {
      background: "#F4F1EA",
      card: "#FCFAF5",
      primary: "#6B2C39",
      accent: "#D4A85D",
    },
    tokens: {
      background: "#F4F1EA",
      foreground: "#2C2825",
      card: "#FCFAF5",
      "card-foreground": "#2C2825",
      popover: "#FCFAF5",
      "popover-foreground": "#2C2825",
      primary: "#6B2C39",
      "primary-foreground": "#FCFAF5",
      secondary: "#F3E8E9",
      "secondary-foreground": "#6B2C39",
      muted: "#E5E0D8",
      "muted-foreground": "#8C8477",
      accent: "#D4A85D",
      "accent-foreground": "#2C2825",
      border: "#E5E0D8",
      input: "#E5E0D8",
      ring: "#6B2C39",
    },
  },
  "industrial-fog": {
    label: "Industrial Fog",
    description: "Cool steel neutrals with strong graphite anchors.",
    preview: {
      background: "#E2E8F0",
      card: "#F8FAFC",
      primary: "#1E293B",
      accent: "#334155",
    },
    tokens: {
      background: "#E2E8F0",
      foreground: "#0F172A",
      card: "#F8FAFC",
      "card-foreground": "#0F172A",
      popover: "#F8FAFC",
      "popover-foreground": "#0F172A",
      primary: "#1E293B",
      "primary-foreground": "#FFFFFF",
      secondary: "#CBD5E1",
      "secondary-foreground": "#1E293B",
      muted: "#E2E8F0",
      "muted-foreground": "#64748B",
      accent: "#334155",
      "accent-foreground": "#FFFFFF",
      border: "#CBD5E1",
      input: "#CBD5E1",
      ring: "#1E293B",
    },
  },
  "brutalist-concrete": {
    label: "Brutalist Concrete",
    description: "Concrete slabs, hard edges, no softness.",
    preview: {
      background: "#C2C2C2",
      card: "#D4D4D4",
      primary: "#000000",
      accent: "#000000",
    },
    tokens: {
      background: "#C2C2C2",
      foreground: "#000000",
      card: "#D4D4D4",
      "card-foreground": "#000000",
      popover: "#D4D4D4",
      "popover-foreground": "#000000",
      primary: "#000000",
      "primary-foreground": "#FFFFFF",
      secondary: "#A3A3A3",
      "secondary-foreground": "#000000",
      muted: "#A3A3A3",
      "muted-foreground": "#525252",
      accent: "#000000",
      "accent-foreground": "#FFFFFF",
      border: "#A3A3A3",
      input: "#A3A3A3",
      ring: "#000000",
      radius: "0rem",
    },
  },
  "sage-retreat": {
    label: "Sage Retreat",
    description: "Muted botanical surfaces with soft olive contrast.",
    preview: {
      background: "#DFE2D9",
      card: "#E9EBE4",
      primary: "#3F4D33",
      accent: "#556246",
    },
    tokens: {
      background: "#DFE2D9",
      foreground: "#2B3024",
      card: "#E9EBE4",
      "card-foreground": "#2B3024",
      popover: "#E9EBE4",
      "popover-foreground": "#2B3024",
      primary: "#3F4D33",
      "primary-foreground": "#E9EBE4",
      secondary: "#D2D6CB",
      "secondary-foreground": "#3F4D33",
      muted: "#D2D6CB",
      "muted-foreground": "#6B7062",
      accent: "#556246",
      "accent-foreground": "#F4F6EF",
      border: "#C5C9BE",
      input: "#C5C9BE",
      ring: "#3F4D33",
    },
  },
  "deep-onyx": {
    label: "Deep Onyx",
    description: "Warm black stone with gilded emphasis.",
    preview: {
      background: "#121110",
      card: "#1C1A19",
      primary: "#CFA16D",
      accent: "#CFA16D",
    },
    tokens: {
      background: "#121110",
      foreground: "#F0EBE1",
      card: "#1C1A19",
      "card-foreground": "#F0EBE1",
      popover: "#1C1A19",
      "popover-foreground": "#F0EBE1",
      primary: "#CFA16D",
      "primary-foreground": "#121110",
      secondary: "#2E2A28",
      "secondary-foreground": "#CFA16D",
      muted: "#2E2A28",
      "muted-foreground": "#8A847E",
      accent: "#CFA16D",
      "accent-foreground": "#121110",
      border: "#2E2A28",
      input: "#403B38",
      ring: "#CFA16D",
    },
  },
  "nordic-abyss": {
    label: "Nordic Abyss",
    description: "Cold navy depth with polar blue focus.",
    preview: {
      background: "#070B14",
      card: "#0D1322",
      primary: "#81A1C1",
      accent: "#81A1C1",
    },
    tokens: {
      background: "#070B14",
      foreground: "#F8FAFC",
      card: "#0D1322",
      "card-foreground": "#F8FAFC",
      popover: "#0D1322",
      "popover-foreground": "#F8FAFC",
      primary: "#81A1C1",
      "primary-foreground": "#070B14",
      secondary: "#1C263B",
      "secondary-foreground": "#81A1C1",
      muted: "#1C263B",
      "muted-foreground": "#64748B",
      accent: "#81A1C1",
      "accent-foreground": "#070B14",
      border: "#1C263B",
      input: "#1C263B",
      ring: "#81A1C1",
    },
  },
  "obsidian": {
    label: "Obsidian",
    description: "Clean monochrome with sharp neutral contrast.",
    preview: {
      background: "#F5F5F4",
      card: "#FFFFFF",
      primary: "#171717",
      accent: "#171717",
    },
    tokens: {
      background: "#F5F5F4",
      foreground: "#171717",
      card: "#FFFFFF",
      "card-foreground": "#171717",
      popover: "#FFFFFF",
      "popover-foreground": "#171717",
      primary: "#171717",
      "primary-foreground": "#FFFFFF",
      secondary: "#F5F5F5",
      "secondary-foreground": "#171717",
      muted: "#F5F5F5",
      "muted-foreground": "#737373",
      accent: "#171717",
      "accent-foreground": "#FFFFFF",
      border: "#E5E5E5",
      input: "#E5E5E5",
      ring: "#171717",
    },
  },
  "emerald-vault": {
    label: "Emerald Vault",
    description: "Dark green treasury with bright mint signals.",
    preview: {
      background: "#022C22",
      card: "#064E3B",
      primary: "#6EE7B7",
      accent: "#10B981",
    },
    tokens: {
      background: "#022C22",
      foreground: "#ECFDF5",
      card: "#064E3B",
      "card-foreground": "#ECFDF5",
      popover: "#064E3B",
      "popover-foreground": "#ECFDF5",
      primary: "#6EE7B7",
      "primary-foreground": "#022C22",
      secondary: "#065F46",
      "secondary-foreground": "#D1FAE5",
      muted: "#065F46",
      "muted-foreground": "#A7F3D0",
      accent: "#10B981",
      "accent-foreground": "#022C22",
      border: "#065F46",
      input: "#065F46",
      ring: "#6EE7B7",
    },
  },
  "ruby-ledger": {
    label: "Ruby Ledger",
    description: "Bright paper with strong rose finance accents.",
    preview: {
      background: "#FFF7F7",
      card: "#FFFFFF",
      primary: "#E11D48",
      accent: "#F43F5E",
    },
    tokens: {
      background: "#FFF7F7",
      foreground: "#171717",
      card: "#FFFFFF",
      "card-foreground": "#171717",
      popover: "#FFFFFF",
      "popover-foreground": "#171717",
      primary: "#E11D48",
      "primary-foreground": "#FFFFFF",
      secondary: "#FFE4E6",
      "secondary-foreground": "#9F1239",
      muted: "#FFE4E6",
      "muted-foreground": "#E11D48",
      accent: "#F43F5E",
      "accent-foreground": "#FFFFFF",
      border: "#FECDD3",
      input: "#FECDD3",
      ring: "#E11D48",
    },
  },
  "midnight-indigo": {
    label: "Midnight Indigo",
    description: "Inky control room with electric cyan accents.",
    preview: {
      background: "#111827",
      card: "#111827",
      primary: "#6366F1",
      accent: "#22D3EE",
    },
    tokens: {
      background: "#111827",
      foreground: "#FFFFFF",
      card: "#111827",
      "card-foreground": "#FFFFFF",
      popover: "#111827",
      "popover-foreground": "#FFFFFF",
      primary: "#6366F1",
      "primary-foreground": "#FFFFFF",
      secondary: "#1E293B",
      "secondary-foreground": "#E0E7FF",
      muted: "#1E293B",
      "muted-foreground": "#94A3B8",
      accent: "#22D3EE",
      "accent-foreground": "#0F172A",
      border: "#312E81",
      input: "#312E81",
      ring: "#6366F1",
    },
  },
  "scandi-pine": {
    label: "Scandi Pine",
    description: "Scandi interior: birch, oat, one forest pine.",
    preview: {
      background: "#F0EADD",
      card: "#FBF5E8",
      primary: "#1B1B1A",
      accent: "#4C7A55",
    },
    tokens: {
      // Semantic Bridge
      background: "#F0EADD",
      foreground: "#1B1B1A",
      card: "#FBF5E8",
      "card-foreground": "#1B1B1A",
      popover: "#FBF5E8",
      "popover-foreground": "#1B1B1A",
      primary: "#1B1B1A",
      "primary-foreground": "#FBF5E8",
      secondary: "#8A8578",
      "secondary-foreground": "#1B1B1A",
      muted: "#F0EADD",
      "muted-foreground": "#8A8578",
      accent: "#4C7A55",
      "accent-foreground": "#FBF5E8",
      border: "#8A8578",
      input: "#8A8578",
      ring: "#4C7A55",

      // BigDrops Specific Tokens
      "bd-app-bg": "#F0EADD",
      "bd-surface": "#FBF5E8",
      "bd-surface-muted": "#F0EADD",
      "bd-border": "#8A8578",
      "bd-border-strong": "#1B1B1A",
      "bd-text": "#1B1B1A",
      "bd-text-muted": "#8A8578",
      "bd-input-bg": "#FBF5E8",
      "bd-input-border": "#8A8578",
      "bd-input-focus": "#4C7A55",
      "bd-card-bg": "#FBF5E8",
      "bd-card-border": "#8A8578",
      "bd-button-primary-bg": "#4C7A55",
      "bd-button-primary-text": "#FBF5E8",
      "bd-button-primary-hover-bg": "#3D6244", // Darker pine
      "bd-nav-active-bg": "#F0EADD",
      "bd-nav-active-text": "#1B1B1A",
      "bd-nav-active-icon": "#4C7A55",
      "bd-surface-action": "#FBF5E8",
      "bd-surface-action-hover": "#F0EADD",
      "bd-surface-action-border": "#8A8578",
      "bd-surface-action-text": "#1B1B1A",
      "bd-surface-action-muted": "#8A8578",
      "bd-action-icon-bg": "#4C7A55",
      "bd-action-icon-text": "#FBF5E8",
      "bd-fab-bg": "#4C7A55",
      "bd-fab-text": "#FBF5E8",

      // Status Fallbacks (Ensuring safety as per rule 4)
      "bd-status-success-bg": "#E9F2EB",
      "bd-status-success-text": "#2D5A3C",
      "bd-status-success-border": "#C9DBCF",
      "bd-status-warning-bg": "#F9F4E8",
      "bd-status-warning-text": "#856404",
      "bd-status-warning-border": "#FFEBA0",
      "bd-status-danger-bg": "#FBEAEB",
      "bd-status-danger-text": "#721C24",
      "bd-status-danger-border": "#F5C6CB",

      // Non-color
      radius: "10px",
      "bd-radius-sm": "3px",
      "bd-radius-md": "6px",
      "bd-radius-lg": "10px",
      "bd-layout-density": "comfortable",
      "bd-layout-padding": "32px",
      "bd-font-family": "'Manrope', 'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-body-size": "0.98rem",
      "bd-label-letter-spacing": "0.22em",

      // Spacing (Scandi Pine specific - Airy 1:2:4 ratio)
      "bd-space-sm": "12px",
      "bd-space-md": "24px",
      "bd-space-lg": "48px",
      "bd-card-padding": "24px",
      "bd-section-gap": "48px",
      "bd-row-gap": "12px",
      "bd-field-gap": "12px",
      "bd-sheet-padding": "24px",
    },
  },
  "swiss-grid": {
    label: "Swiss Grid",
    description: "Helvetica, a 12-column grid, and a single red.",
    preview: {
      background: "#F5F5F5",
      card: "#FFFFFF",
      primary: "#000000",
      accent: "#DC2626",
    },
    tokens: {
      // Semantic Bridge
      background: "#F5F5F5",
      foreground: "#000000",
      card: "#FFFFFF",
      "card-foreground": "#000000",
      popover: "#FFFFFF",
      "popover-foreground": "#000000",
      primary: "#000000",
      "primary-foreground": "#FFFFFF",
      secondary: "#F5F5F5",
      "secondary-foreground": "#555555",
      muted: "#F5F5F5",
      "muted-foreground": "#555555",
      accent: "#DC2626",
      "accent-foreground": "#FFFFFF",
      border: "#555555",
      input: "#555555",
      ring: "#DC2626",
      radius: "0px",

      // BigDrops Specific Tokens
      "bd-app-bg": "#F5F5F5",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#F5F5F5",
      "bd-border": "#555555",
      "bd-border-strong": "#000000",
      "bd-text": "#000000",
      "bd-text-muted": "#555555",
      "bd-text-soft": "#555555",
      "bd-input-bg": "#FFFFFF",
      "bd-input-border": "#555555",
      "bd-input-focus": "#DC2626",
      "bd-card-bg": "#FFFFFF",
      "bd-card-border": "#555555",
      "bd-button-primary-bg": "#DC2626",
      "bd-button-primary-text": "#FFFFFF",
      "bd-button-primary-hover-bg": "#B91C1C",
      "bd-nav-active-bg": "#F5F5F5",
      "bd-nav-active-text": "#000000",
      "bd-nav-active-icon": "#DC2626",
      "bd-surface-action": "#FFFFFF",
      "bd-surface-action-hover": "#F5F5F5",
      "bd-surface-action-border": "#555555",
      "bd-surface-action-text": "#000000",
      "bd-surface-action-muted": "#555555",
      "bd-action-icon-bg": "#DC2626",
      "bd-action-icon-text": "#FFFFFF",
      "bd-fab-bg": "#DC2626",
      "bd-fab-text": "#FFFFFF",

      // Status Fallbacks (Standard but flat)
      "bd-status-success-bg": "#F0FDF4",
      "bd-status-success-text": "#166534",
      "bd-status-success-border": "#DCFCE7",
      "bd-status-warning-bg": "#FFFBEB",
      "bd-status-warning-text": "#92400E",
      "bd-status-warning-border": "#FEF3C7",
      "bd-status-danger-bg": "#FEF2F2",
      "bd-status-danger-text": "#991B1B",
      "bd-status-danger-border": "#FEE2E2",

      // Non-color
      "bd-radius-sm": "0px",
      "bd-radius-md": "0px",
      "bd-radius-lg": "0px",
      "bd-font-family": "'Inter Tight', 'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-body-size": "0.95rem",
      "bd-font-body-line-height": "1.55",
      "bd-font-display-size": "4rem",
      "bd-font-display-weight": "700",
      "bd-font-display-spacing": "-0.03em",
      "bd-font-h1-size": "2.25rem",
      "bd-font-h1-weight": "700",
      "bd-font-h1-spacing": "-0.02em",
      "bd-label-letter-spacing": "0.02em",

      // Spacing
      "bd-space-sm": "8px",
      "bd-space-md": "16px",
      "bd-space-lg": "32px",
      "bd-card-padding": "24px",
      "bd-section-gap": "32px",
      "bd-row-gap": "8px",
      "bd-field-gap": "8px",
      "bd-sheet-padding": "24px",
    },
  },
  "notion-beige": {
    label: "Notion Beige",
    description: "Serene workspace: warm paper and terracotta focus.",
    preview: {
      background: "#F7F6F3",
      card: "#FFFFFF",
      primary: "#191918",
      accent: "#C26B5B",
    },
    tokens: {
      // Semantic Bridge
      background: "#F7F6F3",
      foreground: "#191918",
      card: "#FFFFFF",
      "card-foreground": "#191918",
      popover: "#FFFFFF",
      "popover-foreground": "#191918",
      primary: "#191918",
      "primary-foreground": "#FFFFFF",
      secondary: "#F7F6F3",
      "secondary-foreground": "#8C877D",
      muted: "#F7F6F3",
      "muted-foreground": "#8C877D",
      accent: "#C26B5B",
      "accent-foreground": "#FFFFFF",
      border: "#8C877D",
      input: "#8C877D",
      ring: "#C26B5B",
      radius: "6px",

      // BigDrops Specific Tokens
      "bd-app-bg": "#F7F6F3",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#F7F6F3",
      "bd-border": "#E8E7E4",
      "bd-border-strong": "#8C877D",
      "bd-text": "#191918",
      "bd-text-muted": "#8C877D",
      "bd-text-soft": "#8C877D",
      "bd-input-bg": "#FFFFFF",
      "bd-input-border": "#E8E7E4",
      "bd-input-focus": "#C26B5B",
      "bd-card-bg": "#FFFFFF",
      "bd-card-border": "#E8E7E4",
      "bd-button-primary-bg": "#C26B5B",
      "bd-button-primary-text": "#FFFFFF",
      "bd-button-primary-hover-bg": "#AD5F51",
      "bd-nav-active-bg": "#F7F6F3",
      "bd-nav-active-text": "#191918",
      "bd-nav-active-icon": "#C26B5B",
      "bd-surface-action": "#FFFFFF",
      "bd-surface-action-hover": "#F7F6F3",
      "bd-surface-action-border": "#E8E7E4",
      "bd-action-icon-bg": "#C26B5B",
      "bd-action-icon-text": "#FFFFFF",
      "bd-fab-bg": "#C26B5B",
      "bd-fab-text": "#FFFFFF",

      // Non-color
      "bd-radius-sm": "4px",
      "bd-radius-md": "6px",
      "bd-radius-lg": "10px",
      "bd-font-family": "'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-display-family": "'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-h1-family": "'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-label-family": "'Inter', ui-sans-serif, system-ui, sans-serif",
      "bd-font-body-size": "0.95rem",
      "bd-font-body-line-height": "1.6",
      "bd-font-display-size": "3.5rem",
      "bd-font-display-weight": "700",
      "bd-font-display-spacing": "-0.03em",
      "bd-font-h1-size": "2rem",
      "bd-font-h1-weight": "700",
      "bd-font-h1-spacing": "-0.02em",
      "bd-label-letter-spacing": "0.02em",

      "bd-space-sm": "8px",
      "bd-space-md": "16px",
      "bd-space-lg": "32px",
      "bd-card-padding": "24px",
    },
  },
  "science-journal": {
    label: "Science Journal",
    description: "Academic rigor: crisp serifs and deep navy data focus.",
    preview: {
      background: "#FAF9F5",
      card: "#FFFFFF",
      primary: "#121213",
      accent: "#1A4B8C",
    },
    tokens: {
      // Semantic Bridge
      background: "#FAF9F5",
      foreground: "#121213",
      card: "#FFFFFF",
      "card-foreground": "#121213",
      popover: "#FFFFFF",
      "popover-foreground": "#121213",
      primary: "#121213",
      "primary-foreground": "#FFFFFF",
      secondary: "#FAF9F5",
      "secondary-foreground": "#606368",
      muted: "#F5F3ED",
      "muted-foreground": "#606368",
      accent: "#1A4B8C",
      "accent-foreground": "#FFFFFF",
      border: "#E0DDD5",
      input: "#E0DDD5",
      ring: "#1A4B8C",
      radius: "3px",

      // BigDrops Specific Tokens
      "bd-app-bg": "#FAF9F5",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#F5F3ED",
      "bd-border": "#E0DDD5",
      "bd-border-strong": "#121213",
      "bd-text": "#121213",
      "bd-text-muted": "#606368",
      "bd-text-soft": "#808080",
      "bd-input-bg": "#FFFFFF",
      "bd-input-border": "#E0DDD5",
      "bd-input-focus": "#1A4B8C",
      "bd-card-bg": "#FFFFFF",
      "bd-card-border": "#E0DDD5",
      "bd-button-primary-bg": "#1A4B8C",
      "bd-button-primary-text": "#FFFFFF",
      "bd-button-primary-hover-bg": "#153D72",
      "bd-nav-active-bg": "#F5F3ED",
      "bd-nav-active-text": "#121213",
      "bd-nav-active-icon": "#1A4B8C",
      "bd-surface-action": "#FFFFFF",
      "bd-surface-action-hover": "#F5F3ED",
      "bd-action-icon-bg": "#1A4B8C",
      "bd-action-icon-text": "#FFFFFF",
      "bd-fab-bg": "#1A4B8C",
      "bd-fab-text": "#FFFFFF",

      // Non-color
      "bd-radius-sm": "2px",
      "bd-radius-md": "3px",
      "bd-radius-lg": "5px",
      "bd-font-family": "'Source Serif 4', serif",
      "bd-font-display-family": "'Source Serif 4', serif",
      "bd-font-h1-family": "'Source Serif 4', serif",
      "bd-font-label-family": "'IBM Plex Sans', sans-serif",
      "bd-font-body-size": "1rem",
      "bd-font-body-line-height": "1.7",
      "bd-font-display-size": "4rem",
      "bd-font-display-weight": "700",
      "bd-font-display-spacing": "-0.015em",
      "bd-font-h1-size": "2.2rem",
      "bd-font-h1-weight": "700",
      "bd-font-h1-spacing": "0em",
      "bd-label-letter-spacing": "0.08em",

      "bd-space-sm": "10px",
      "bd-space-md": "20px",
      "bd-space-lg": "40px",
      "bd-card-padding": "32px",
    },
  },
  "oss-terminal": {
    label: "OSS Terminal",
    description: "Dev productivity: technical neutrals with electric violet focus.",
    preview: {
      background: "#F6F1E7",
      card: "#FBF6EA",
      primary: "#161614",
      accent: "#8957E5",
    },
    tokens: {
      // Semantic Bridge
      background: "#F6F1E7",
      foreground: "#161614",
      card: "#FBF6EA",
      "card-foreground": "#161614",
      popover: "#FBF6EA",
      "popover-foreground": "#161614",
      primary: "#161614",
      "primary-foreground": "#FBF6EA",
      secondary: "#F6F1E7",
      "secondary-foreground": "#6A6860",
      muted: "#F0EBE0",
      "muted-foreground": "#6A6860",
      accent: "#8957E5",
      "accent-foreground": "#FFFFFF",
      border: "#EAE3D4",
      input: "#EAE3D4",
      ring: "#8957E5",
      radius: "6px",

      // BigDrops Specific Tokens
      "bd-app-bg": "#F6F1E7",
      "bd-surface": "#FBF6EA",
      "bd-surface-muted": "#F0EBE0",
      "bd-border": "#EAE3D4",
      "bd-border-strong": "#161614",
      "bd-text": "#161614",
      "bd-text-muted": "#6A6860",
      "bd-text-soft": "#807D73",
      "bd-input-bg": "#FBF6EA",
      "bd-input-border": "#EAE3D4",
      "bd-input-focus": "#8957E5",
      "bd-card-bg": "#FBF6EA",
      "bd-card-border": "#EAE3D4",
      "bd-button-primary-bg": "#8957E5",
      "bd-button-primary-text": "#FBF6EA",
      "bd-button-primary-hover-bg": "#7540D1",
      "bd-nav-active-bg": "#F0EBE0",
      "bd-nav-active-text": "#161614",
      "bd-nav-active-icon": "#8957E5",
      "bd-surface-action": "#FBF6EA",
      "bd-surface-action-hover": "#F0EBE0",
      "bd-action-icon-bg": "#8957E5",
      "bd-action-icon-text": "#FBF6EA",
      "bd-fab-bg": "#8957E5",
      "bd-fab-text": "#FBF6EA",

      // Non-color
      "bd-radius-sm": "4px",
      "bd-radius-md": "6px",
      "bd-radius-lg": "10px",
      "bd-font-family": "'IBM Plex Sans', sans-serif",
      "bd-font-display-family": "'JetBrains Mono', monospace",
      "bd-font-h1-family": "'JetBrains Mono', monospace",
      "bd-font-label-family": "'JetBrains Mono', monospace",
      "bd-font-body-size": "0.95rem",
      "bd-font-body-line-height": "1.65",
      "bd-font-display-size": "3.25rem",
      "bd-font-display-weight": "700",
      "bd-font-display-spacing": "-0.02em",
      "bd-font-h1-size": "1.7rem",
      "bd-font-h1-weight": "600",
      "bd-font-h1-spacing": "0em",
      "bd-label-letter-spacing": "0.04em",

      "bd-space-sm": "8px",
      "bd-space-md": "16px",
      "bd-space-lg": "32px",
      "bd-card-padding": "24px",
    },
  },
  "the-sun": {
    label: "The Sun",
    description: "Bold editorial: high-impact headlines and deep red action.",
    preview: {
      background: "#EFEAE0",
      card: "#FFFFFF",
      primary: "#0A0A0A",
      accent: "#E30613",
    },
    tokens: {
      // Semantic Bridge
      background: "#EFEAE0",
      foreground: "#0A0A0A",
      card: "#FFFFFF",
      "card-foreground": "#0A0A0A",
      popover: "#FFFFFF",
      "popover-foreground": "#0A0A0A",
      primary: "#0A0A0A",
      "primary-foreground": "#FFFFFF",
      secondary: "#EFEAE0",
      "secondary-foreground": "#555555",
      muted: "#E8E2D4",
      "muted-foreground": "#555555",
      accent: "#E30613",
      "accent-foreground": "#FFFFFF",
      border: "#DED7C8",
      input: "#DED7C8",
      ring: "#E30613",
      radius: "0px",

      // BigDrops Specific Tokens
      "bd-app-bg": "#EFEAE0",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#E8E2D4",
      "bd-border": "#DED7C8",
      "bd-border-strong": "#0A0A0A",
      "bd-text": "#0A0A0A",
      "bd-text-muted": "#555555",
      "bd-text-soft": "#707070",
      "bd-input-bg": "#FFFFFF",
      "bd-input-border": "#DED7C8",
      "bd-input-focus": "#E30613",
      "bd-card-bg": "#FFFFFF",
      "bd-card-border": "#DED7C8",
      "bd-button-primary-bg": "#E30613",
      "bd-button-primary-text": "#FFFFFF",
      "bd-button-primary-hover-bg": "#C40510",
      "bd-nav-active-bg": "#E8E2D4",
      "bd-nav-active-text": "#0A0A0A",
      "bd-nav-active-icon": "#E30613",
      "bd-surface-action": "#FFFFFF",
      "bd-surface-action-hover": "#E8E2D4",
      "bd-action-icon-bg": "#E30613",
      "bd-action-icon-text": "#FFFFFF",
      "bd-fab-bg": "#E30613",
      "bd-fab-text": "#FFFFFF",

      // Non-color
      "bd-radius-sm": "0px",
      "bd-radius-md": "0px",
      "bd-radius-lg": "2px",
      "bd-font-family": "'Source Serif 4', serif",
      "bd-font-display-family": "'Anton', sans-serif",
      "bd-font-h1-family": "'Anton', sans-serif",
      "bd-font-label-family": "'Anton', sans-serif",
      "bd-font-body-size": "0.98rem",
      "bd-font-body-line-height": "1.55",
      "bd-font-display-size": "6rem",
      "bd-font-display-weight": "400",
      "bd-font-display-spacing": "-0.02em",
      "bd-font-h1-size": "3rem",
      "bd-font-h1-weight": "400",
      "bd-font-h1-spacing": "0em",
      "bd-label-letter-spacing": "0.08em",

      "bd-space-sm": "8px",
      "bd-space-md": "16px",
      "bd-space-lg": "32px",
      "bd-card-padding": "24px",
    },
  },
  "blackrock": {
    label: "BlackRock",
    description: "Institutional authority: cream paper and deep charcoal.",
    preview: {
      background: "#F4F1EA",
      card: "#FFFFFF",
      primary: "#111111",
      accent: "#111111",
    },
    tokens: {
      background: "#F4F1EA",
      foreground: "#111111",
      card: "#FFFFFF",
      "card-foreground": "#111111",
      primary: "#111111",
      "primary-foreground": "#F4F1EA",
      secondary: "#F4F1EA",
      "secondary-foreground": "#666666",
      muted: "#E5E1D8",
      "muted-foreground": "#666666",
      accent: "#111111",
      "accent-foreground": "#FFFFFF",
      border: "#D1CDC2",
      input: "#D1CDC2",
      ring: "#111111",
      radius: "0px",
      "bd-app-bg": "#F4F1EA",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#E5E1D8",
      "bd-border": "#D1CDC2",
      "bd-border-strong": "#111111",
      "bd-text": "#111111",
      "bd-text-muted": "#666666",
      "bd-input-bg": "#FFFFFF",
      "bd-button-primary-bg": "#111111",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "0px",
      "bd-radius-md": "0px",
      "bd-radius-lg": "0px",
      "bd-font-family": "'Inter', sans-serif",
      "bd-font-h1-family": "'Playfair Display', serif",
      "bd-font-display-family": "'Playfair Display', serif",
      "bd-font-h1-weight": "700",
    },
  },
  "ramp": {
    label: "Ramp",
    description: "Modern fintech: crisp white and electric violet.",
    preview: {
      background: "#FFFFFF",
      card: "#F6F9FC",
      primary: "#000000",
      accent: "#635BFF",
    },
    tokens: {
      background: "#FFFFFF",
      foreground: "#000000",
      card: "#F6F9FC",
      "card-foreground": "#000000",
      primary: "#000000",
      "primary-foreground": "#FFFFFF",
      secondary: "#F6F9FC",
      "secondary-foreground": "#6B7280",
      muted: "#F3F4F6",
      "muted-foreground": "#6B7280",
      accent: "#635BFF",
      "accent-foreground": "#FFFFFF",
      border: "#E5E7EB",
      input: "#E5E7EB",
      ring: "#635BFF",
      radius: "8px",
      "bd-app-bg": "#FFFFFF",
      "bd-surface": "#F6F9FC",
      "bd-surface-muted": "#F3F4F6",
      "bd-border": "#E5E7EB",
      "bd-border-strong": "#000000",
      "bd-text": "#000000",
      "bd-text-muted": "#6B7280",
      "bd-input-bg": "#FFFFFF",
      "bd-button-primary-bg": "#635BFF",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "4px",
      "bd-radius-md": "8px",
      "bd-radius-lg": "12px",
      "bd-font-family": "'Inter', sans-serif",
    },
  },
  "binance": {
    label: "Binance",
    description: "Digital assets: deep carbon and signature gold.",
    preview: {
      background: "#0B0E11",
      card: "#1E2329",
      primary: "#FCD535",
      accent: "#FCD535",
    },
    tokens: {
      background: "#0B0E11",
      foreground: "#EAECEF",
      card: "#1E2329",
      "card-foreground": "#EAECEF",
      primary: "#FCD535",
      "primary-foreground": "#0B0E11",
      secondary: "#0B0E11",
      "secondary-foreground": "#848E9C",
      muted: "#1E2329",
      "muted-foreground": "#848E9C",
      accent: "#FCD535",
      "accent-foreground": "#0B0E11",
      border: "#474D57",
      input: "#474D57",
      ring: "#FCD535",
      radius: "4px",
      "bd-app-bg": "#0B0E11",
      "bd-surface": "#1E2329",
      "bd-surface-muted": "#0B0E11",
      "bd-border": "#474D57",
      "bd-border-strong": "#FCD535",
      "bd-text": "#EAECEF",
      "bd-text-muted": "#848E9C",
      "bd-input-bg": "#1E2329",
      "bd-button-primary-bg": "#FCD535",
      "bd-button-primary-text": "#0B0E11",
      "bd-radius-sm": "2px",
      "bd-radius-md": "4px",
      "bd-radius-lg": "8px",
      "bd-font-family": "'Inter', sans-serif",
    },
  },
  "uber": {
    label: "Uber",
    description: "Universal mobility: stark monochrome and low radius.",
    preview: {
      background: "#FFFFFF",
      card: "#FFFFFF",
      primary: "#000000",
      accent: "#000000",
    },
    tokens: {
      background: "#FFFFFF",
      foreground: "#000000",
      card: "#FFFFFF",
      "card-foreground": "#000000",
      primary: "#000000",
      "primary-foreground": "#FFFFFF",
      secondary: "#FFFFFF",
      "secondary-foreground": "#666666",
      muted: "#EEEEEE",
      "muted-foreground": "#666666",
      accent: "#000000",
      "accent-foreground": "#FFFFFF",
      border: "#000000",
      input: "#000000",
      ring: "#000000",
      radius: "0px",
      "bd-app-bg": "#FFFFFF",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#EEEEEE",
      "bd-border": "#000000",
      "bd-border-strong": "#000000",
      "bd-text": "#000000",
      "bd-text-muted": "#666666",
      "bd-input-bg": "#FFFFFF",
      "bd-button-primary-bg": "#000000",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "0px",
      "bd-radius-md": "0px",
      "bd-radius-lg": "0px",
      "bd-font-family": "'Inter', sans-serif",
    },
  },
  "bmw": {
    label: "BMW",
    description: "Automotive luxury: black finish with M-series blue.",
    preview: {
      background: "#000000",
      card: "#1C1C1C",
      primary: "#FFFFFF",
      accent: "#0066B3",
    },
    tokens: {
      background: "#000000",
      foreground: "#FFFFFF",
      card: "#1C1C1C",
      "card-foreground": "#FFFFFF",
      primary: "#FFFFFF",
      "primary-foreground": "#000000",
      secondary: "#000000",
      "secondary-foreground": "#A0A0A0",
      muted: "#1C1C1C",
      "muted-foreground": "#A0A0A0",
      accent: "#0066B3",
      "accent-foreground": "#FFFFFF",
      border: "#333333",
      input: "#333333",
      ring: "#0066B3",
      radius: "4px",
      "bd-app-bg": "#000000",
      "bd-surface": "#1C1C1C",
      "bd-surface-muted": "#111111",
      "bd-border": "#333333",
      "bd-border-strong": "#FFFFFF",
      "bd-text": "#FFFFFF",
      "bd-text-muted": "#A0A0A0",
      "bd-input-bg": "#1C1C1C",
      "bd-button-primary-bg": "#0066B3",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "2px",
      "bd-radius-md": "4px",
      "bd-radius-lg": "8px",
      "bd-font-family": "'Inter', sans-serif",
    },
  },
  "grand-budapest": {
    label: "Grand Budapest",
    description: "Lobby elegance: dusty pink, maroon, and classic serif.",
    preview: {
      background: "#F8D7DA",
      card: "#FFFFFF",
      primary: "#8C1C1C",
      accent: "#DC2626",
    },
    tokens: {
      background: "#F8D7DA",
      foreground: "#8C1C1C",
      card: "#FFFFFF",
      "card-foreground": "#8C1C1C",
      primary: "#8C1C1C",
      "primary-foreground": "#FFFFFF",
      secondary: "#F8D7DA",
      "secondary-foreground": "#D9B48F",
      muted: "#F0C4C9",
      "muted-foreground": "#D9B48F",
      accent: "#DC2626",
      "accent-foreground": "#FFFFFF",
      border: "#D9B48F",
      input: "#D9B48F",
      ring: "#8C1C1C",
      radius: "12px",
      "bd-app-bg": "#F8D7DA",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#F0C4C9",
      "bd-border": "#D9B48F",
      "bd-border-strong": "#8C1C1C",
      "bd-text": "#8C1C1C",
      "bd-text-muted": "#D9B48F",
      "bd-input-bg": "#FFFFFF",
      "bd-button-primary-bg": "#DC2626",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "4px",
      "bd-radius-md": "12px",
      "bd-radius-lg": "24px",
      "bd-font-family": "'Playfair Display', serif",
      "bd-font-h1-family": "'Playfair Display', serif",
      "bd-font-display-family": "'Playfair Display', serif",
    },
  },
  "aqua-mint": {
    label: "Aqua Mint",
    description: "Coastal clarity: refreshing mint and deep ocean teal.",
    preview: {
      background: "#E0FFF7",
      card: "#FFFFFF",
      primary: "#004D40",
      accent: "#00BFA5",
    },
    tokens: {
      background: "#E0FFF7",
      foreground: "#004D40",
      card: "#FFFFFF",
      "card-foreground": "#004D40",
      primary: "#004D40",
      "primary-foreground": "#FFFFFF",
      secondary: "#E0FFF7",
      "secondary-foreground": "#4DB6AC",
      muted: "#B2DFDB",
      "muted-foreground": "#4DB6AC",
      accent: "#00BFA5",
      "accent-foreground": "#FFFFFF",
      border: "#4DB6AC",
      input: "#4DB6AC",
      ring: "#004D40",
      radius: "24px",
      "bd-app-bg": "#E0FFF7",
      "bd-surface": "#FFFFFF",
      "bd-surface-muted": "#B2DFDB",
      "bd-border": "#4DB6AC",
      "bd-border-strong": "#004D40",
      "bd-text": "#004D40",
      "bd-text-muted": "#4DB6AC",
      "bd-input-bg": "#FFFFFF",
      "bd-button-primary-bg": "#00BFA5",
      "bd-button-primary-text": "#FFFFFF",
      "bd-radius-sm": "8px",
      "bd-radius-md": "24px",
      "bd-radius-lg": "48px",
      "bd-font-family": "'DM Sans', sans-serif",
    },
  },
}

export const THEME_PRESETS: ThemePresetDefinition[] = FIXED_THEME_PRESET_IDS.map((id) => {
  const preset = PRESET_SOURCE[id]
  return {
    id,
    label: preset.label,
    description: preset.description,
    preview: preset.preview,
    bundle: normalizeThemeTokenBundle(preset.tokens, { allowRadius: true }),
  }
})

export function isFixedThemePresetId(value: unknown): value is FixedThemePresetId {
  return typeof value === "string" && FIXED_THEME_PRESET_IDS.includes(value as FixedThemePresetId)
}

export function getThemePreset(id: unknown): ThemePresetDefinition | null {
  if (!isFixedThemePresetId(id)) return null
  return THEME_PRESETS.find((preset) => preset.id === id) ?? null
}

export function resolveThemeMode(
  settings: {
    app_theme_preset_id?: unknown
    app_background_color?: unknown
    app_card_color?: unknown
    app_theme_tokens?: unknown
  } | null | undefined,
): ThemeMode {
  const presetId = settings?.app_theme_preset_id
  if (presetId === "custom" || isFixedThemePresetId(presetId)) return presetId

  // Backwards compatibility: explicit manual values should still behave as custom mode.
  if (settings?.app_background_color || settings?.app_card_color || settings?.app_theme_tokens) {
    return "custom"
  }

  return BASE_THEME_MODE
}
