import { StyleSheet } from '@react-pdf/renderer'
import { TEMPLATE_TOKENS } from './templateTokens'
import type { RefrensTemplateId } from './types'

export function createTemplateStyles(templateId: RefrensTemplateId) {
  const tokens = TEMPLATE_TOKENS[templateId]
  const isDarkHeader = templateId === 'modern' || templateId === 'bold'

  return StyleSheet.create({
    page: {
      paddingTop: 32,
      paddingRight: 32,
      paddingBottom: 28,
      paddingLeft: 32,
      backgroundColor: tokens.pageBackground,
      color: tokens.bodyText,
      fontFamily: 'Helvetica',
      fontSize: 10,
    },
    headerWrap: {
      backgroundColor: tokens.headerBackground,
      color: tokens.headerText,
      paddingTop: isDarkHeader ? 20 : 0,
      paddingRight: isDarkHeader ? 20 : 0,
      paddingBottom: 20,
      paddingLeft: isDarkHeader ? 20 : 0,
      marginTop: isDarkHeader ? -32 : 0,
      marginRight: isDarkHeader ? -32 : 0,
      marginBottom: 20,
      marginLeft: isDarkHeader ? -32 : 0,
      borderBottomWidth: isDarkHeader ? 0 : templateId === 'minimal' ? 1 : 3,
      borderBottomColor: tokens.headerBand,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 24,
    },
    headerBusiness: {
      flex: 1,
      minHeight: 70,
    },
    businessName: {
      fontSize: 17,
      fontFamily: 'Helvetica-Bold',
      color: templateId === 'elegant' ? tokens.accent : tokens.headerText,
      marginBottom: 5,
      lineHeight: 1.2,
    },
    businessTagline: {
      fontSize: 10,
      color: tokens.headerMuted,
      marginBottom: 4,
      lineHeight: 1.5,
    },
    businessLine: {
      fontSize: 10,
      color: tokens.headerMuted,
      lineHeight: 1.55,
      maxWidth: 270,
    },
    headerMeta: {
      flexShrink: 0,
      width: 190,
      alignItems: 'flex-end',
    },
    logo: {
      maxWidth: 150,
      maxHeight: 72,
      objectFit: 'contain',
      marginBottom: 10,
    },
    documentLabel: {
      fontSize: 14,
      fontFamily: 'Helvetica-Bold',
      color: isDarkHeader ? 'rgba(255,255,255,0.92)' : tokens.accent,
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 2,
    },
    documentNumber: {
      fontSize: 13,
      fontFamily: 'Helvetica-Bold',
      color: tokens.headerText,
      marginBottom: 6,
    },
    metaRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 4,
      marginTop: 2,
    },
    metaLabel: {
      fontSize: 10,
      color: isDarkHeader ? tokens.headerMuted : '#6b7280',
    },
    metaValue: {
      fontSize: 10,
      fontFamily: 'Helvetica-Bold',
      color: tokens.headerText,
      maxWidth: 120,
      textAlign: 'right',
    },
    title: {
      fontSize: 12.5,
      fontFamily: 'Helvetica-Bold',
      color: '#111827',
      marginBottom: 12,
      lineHeight: 1.3,
    },
    partiesWrap: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    partyCard: {
      flex: 1,
      borderWidth: 1,
      borderColor: tokens.subtleBorder,
      borderRadius: 8,
      padding: 12,
      backgroundColor: tokens.cardBackground,
    },
    partyLabel: {
      fontSize: 8.5,
      fontFamily: 'Helvetica-Bold',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      color: '#9ca3af',
      marginBottom: 5,
    },
    partyName: {
      fontSize: 12,
      fontFamily: 'Helvetica-Bold',
      color: '#111827',
      marginBottom: 4,
      lineHeight: 1.3,
    },
    partyLine: {
      fontSize: 10.3,
      color: tokens.bodyText,
      lineHeight: 1.5,
    },
    table: {
      marginBottom: 0,
    },
    tableHeader: {
      flexDirection: 'row',
      borderTopWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
      backgroundColor: tokens.tableHeaderBackground,
      paddingVertical: 7,
      paddingHorizontal: 9,
    },
    thText: {
      fontSize: 7.8,
      fontFamily: 'Helvetica-Bold',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      color: tokens.tableHeaderText,
    },
    tableRow: {
      flexDirection: 'row',
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
      paddingVertical: 7,
      paddingHorizontal: 9,
      backgroundColor: '#ffffff',
    },
    tableRowAlt: {
      flexDirection: 'row',
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
      paddingVertical: 7,
      paddingHorizontal: 9,
      backgroundColor: templateId === 'elegant' ? '#fffaf0' : '#f9fafb',
    },
    groupRow: {
      flexDirection: 'row',
      backgroundColor: tokens.tableHeaderBackground,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
      paddingVertical: 7,
      paddingHorizontal: 9,
    },
    groupText: {
      fontSize: 8.2,
      fontFamily: 'Helvetica-Bold',
      color: tokens.tableHeaderText,
      textTransform: 'uppercase',
    },
    groupSubtotalRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
      paddingVertical: 7,
      paddingHorizontal: 9,
      backgroundColor: templateId === 'elegant' ? '#fff7ed' : '#fafafa',
    },
    groupSubtotalLabel: {
      fontSize: 7.8,
      fontFamily: 'Helvetica-Bold',
      color: tokens.bodyText,
      marginRight: 10,
    },
    groupSubtotalValue: {
      fontSize: 7.8,
      fontFamily: 'Helvetica-Bold',
      color: '#111827',
    },
    descText: {
      fontSize: 10.2,
      fontFamily: 'Helvetica-Bold',
      color: '#111827',
      lineHeight: 1.3,
    },
    subDescText: {
      fontSize: 8.7,
      color: tokens.mutedText,
      marginTop: 2,
      lineHeight: 1.4,
    },
    totalsWrap: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 0,
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderColor: tokens.tableBorder,
    },
    totalsBox: {
      width: 280,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderLeftWidth: 1,
      borderLeftColor: tokens.tableBorder,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
      paddingVertical: 3,
    },
    totalLabel: {
      fontSize: 11,
      color: tokens.bodyText,
    },
    totalValue: {
      fontSize: 11,
      color: tokens.bodyText,
      fontFamily: 'Helvetica',
      textAlign: 'right',
    },
    totalDivider: {
      borderTopWidth: 1,
      borderTopColor: tokens.tableBorder,
      marginTop: 5,
      paddingTop: 8,
    },
    grandRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
      borderTopWidth: 2,
      borderTopColor: tokens.accent,
      marginTop: 7,
      paddingTop: 8,
      paddingBottom: 2,
    },
    grandLabel: {
      fontSize: 13,
      fontFamily: 'Helvetica-Bold',
      color: tokens.grandTotalColor,
    },
    grandValue: {
      fontSize: 13,
      fontFamily: 'Helvetica-Bold',
      color: tokens.grandTotalColor,
      textAlign: 'right',
    },
    balanceLabel: {
      fontSize: 11,
      fontFamily: 'Helvetica-Bold',
      color: '#dc2626',
    },
    balanceValue: {
      fontSize: 11,
      fontFamily: 'Helvetica-Bold',
      color: '#dc2626',
      textAlign: 'right',
    },
    amountWordsBox: {
      marginTop: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      backgroundColor: tokens.amountWordsBackground,
      borderWidth: 1,
      borderColor: tokens.amountWordsBorder,
      borderRadius: 6,
    },
    amountWordsLead: {
      fontSize: 8.8,
      fontFamily: 'Helvetica-Bold',
      color: tokens.accent,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    amountWordsText: {
      fontSize: 10,
      color: tokens.bodyText,
      marginTop: 3,
      lineHeight: 1.45,
    },
    supportWrap: {
      flexDirection: 'row',
      gap: 16,
      marginTop: 16,
      fontSize: 11,
    },
    supportColumn: {
      flex: 1.2,
    },
    signatureColumn: {
      flex: 1,
      justifyContent: 'space-between',
      minHeight: 120,
    },
    supportTitle: {
      fontSize: 8.5,
      fontFamily: 'Helvetica-Bold',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      color: '#9ca3af',
      marginBottom: 6,
    },
    supportBox: {
      borderWidth: 1,
      borderColor: tokens.tableBorder,
      borderRadius: 6,
      padding: 10,
      marginBottom: 10,
      backgroundColor: templateId === 'elegant' ? '#fffaf0' : '#ffffff',
    },
    supportRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 3,
    },
    supportLabel: {
      width: 72,
      fontSize: 10.3,
      color: '#9ca3af',
    },
    supportValue: {
      flex: 1,
      fontSize: 10.3,
      color: tokens.bodyText,
      lineHeight: 1.6,
    },
    supportText: {
      fontSize: 10.3,
      color: tokens.bodyText,
      lineHeight: 1.6,
    },
    linkText: {
      fontSize: 10.3,
      color: tokens.accent,
      textDecoration: 'underline',
      lineHeight: 1.5,
      marginBottom: 4,
    },
    signatureHint: {
      fontSize: 9,
      color: '#9ca3af',
      textAlign: 'right',
    },
    signatureBlock: {
      alignItems: 'flex-end',
      marginTop: 20,
    },
    signatureName: {
      fontSize: 10.3,
      fontFamily: 'Helvetica-Bold',
      color: tokens.bodyText,
      marginBottom: 6,
    },
    signatureLine: {
      width: 160,
      borderBottomWidth: 1,
      borderBottomColor: '#d1d5db',
      paddingBottom: 28,
      marginBottom: 6,
    },
    signatureImage: {
      width: 120,
      height: 40,
      objectFit: 'contain',
      marginBottom: 6,
    },
    signatureRole: {
      fontSize: 10,
      color: '#9ca3af',
      textAlign: 'right',
    },
    footerNote: {
      marginTop: 20,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: tokens.footerBorder,
      textAlign: 'center',
      fontSize: 8.5,
      color: '#9ca3af',
      lineHeight: 1.5,
    },
  })
}
