import test from 'node:test'
import assert from 'node:assert/strict'

import { adaptIndustryData } from '../../components/pdf-new/industryAdapter.ts'

function createPdfModel(kind) {
  return {
    identity: {
      id: `${kind}-1`,
      kind,
      number: kind === 'invoice' ? 'INV-001' : 'QUO-001',
      title: kind === 'invoice' ? 'Invoice' : 'Quotation',
      issueDate: '2026-04-16',
      dueDate: kind === 'invoice' ? '2026-04-30' : undefined,
      validUntil: kind === 'quotation' ? '2026-04-30' : undefined,
      currency: 'NGN',
    },
    issuer: {
      label: 'From',
      name: 'Bigdrops Energy',
      addressLines: ['12 Power Lane', 'Lagos'],
      phone: '+2348000000000',
      email: 'hello@bigdrops.test',
    },
    recipient: {
      label: kind === 'invoice' ? 'Bill To' : 'Prepared For',
      name: 'Acme Client',
      addressLines: ['24 Client Road', 'Abuja'],
      phone: '+2348111111111',
      email: 'client@example.com',
    },
    headerFields: [
      { label: kind === 'invoice' ? 'Due Date' : 'Valid Until', value: '2026-04-30' },
    ],
    columns: [
      { key: 'description', label: 'Description', kind: 'builtin', align: 'left' },
      { key: 'quantity', label: 'Qty', kind: 'builtin', align: 'center' },
      { key: 'unit_price', label: 'Unit Price', kind: 'builtin', align: 'right' },
      { key: 'amount', label: 'Amount', kind: 'builtin', align: 'right' },
    ],
    items: [
      {
        id: `${kind}-item-1`,
        rowType: 'line',
        description: 'Solar panel installation',
        subDescription: 'Roof-mounted system',
        quantity: 2,
        unit: 'pcs',
        unitPrice: 150000,
        amount: 300000,
      },
    ],
    totals: {
      mode: 'standard',
      rows: [
        { key: 'subtotal', label: 'Subtotal', amount: 300000 },
        { key: 'total', label: 'Total', amount: 300000, emphasis: true },
      ],
      amountInWords: 'Three hundred thousand naira only',
    },
    notes: {
      title: 'Notes',
      content: 'Thanks for your business.',
      format: 'text',
    },
    terms: {
      title: 'Terms',
      content: 'Payment due within 14 days.',
      format: 'text',
    },
    signature: {
      name: 'Jane Doe',
      role: 'Operations Lead',
    },
    footerText: 'Generated by Bigdrops',
    metaFooter: {
      companyName: 'Bigdrops Energy',
    },
    logo: null,
    template: null,
  }
}

test('adaptIndustryData formats pdf money values through the shared safe formatter path', () => {
  const data = adaptIndustryData({
    ...createPdfModel('invoice'),
    columns: [
      { key: 'num', label: '#', kind: 'builtin', align: 'center', pdfWidth: 20 },
      { key: 'description', label: 'Description', kind: 'builtin', align: 'left', pdfFlex: 3 },
      { key: 'unit_price', label: 'Unit Price', kind: 'builtin', align: 'right', pdfWidth: 54 },
      { key: 'amount', label: 'Amount', kind: 'builtin', align: 'right', pdfWidth: 62 },
    ],
    items: [
      {
        id: 'invoice-item-1',
        rowType: 'line',
        description: 'Solar panel installation',
        subDescription: 'Roof-mounted system',
        quantity: 2,
        unitPrice: 150000,
        amount: 300000,
        cells: {
          num: '1',
          description: 'Solar panel installation',
          unit_price: '150000',
          amount: '300000',
        },
      },
    ],
    totals: {
      mode: 'standard',
      rows: [
        { key: 'subtotal', label: 'Subtotal', amount: 300000 },
        { key: 'total', label: 'Total', amount: 300000, emphasis: true },
      ],
      amountInWords: 'Three hundred thousand naira only',
    },
  })

  assert.equal(data.table.rows[0].cells.num, '1')
  assert.equal(data.table.rows[0].cells.unit_price, '150,000')
  assert.equal(data.table.rows[0].cells.amount, '300,000')
  assert.equal(data.totals.lines[0].value, 'NGN 300,000')
  assert.equal(data.totals.mainLine.value, 'NGN 300,000')
})

test('adaptIndustryData preserves grouped subtotal presentation when a group header enables it', () => {
  const data = adaptIndustryData({
    ...createPdfModel('invoice'),
    columns: [
      { key: 'num', label: '#', kind: 'builtin', align: 'center', pdfWidth: 20 },
      { key: 'description', label: 'Description', kind: 'builtin', align: 'left', pdfFlex: 3 },
      { key: 'amount', label: 'Amount', kind: 'builtin', align: 'right', pdfWidth: 62 },
    ],
    items: [
      {
        id: 'group-1',
        rowType: 'group_header',
        groupId: 'group-1',
        groupLabel: 'Solar Works',
        customData: {
          showSubtotal: true,
        },
      },
      {
        id: 'line-1',
        rowType: 'line',
        groupId: 'group-1',
        description: 'Panel supply',
        amount: 125000,
        cells: {
          num: '1',
          description: 'Panel supply',
          amount: '125000',
        },
      },
      {
        id: 'line-2',
        rowType: 'line',
        groupId: 'group-1',
        description: 'Mounting kit',
        amount: 75000,
        cells: {
          num: '2',
          description: 'Mounting kit',
          amount: '75000',
        },
      },
    ],
  })

  assert.equal(data.table.rows[0].isGroupHeader, true)
  assert.equal(data.table.rows[0].showSubtotal, true)
  assert.equal(data.table.rows[0].groupSubtotalLabel, null)
  assert.equal(data.table.rows[0].groupSubtotalValue, 'NGN 200,000')
})

test('adaptIndustryData strips html markup from notes and terms before the PDF template renders them', () => {
  const data = adaptIndustryData({
    ...createPdfModel('quotation'),
    notes: {
      title: 'Notes',
      content: '<p>Hello <strong>team</strong><br />Thanks</p>',
      format: 'html',
    },
    terms: {
      title: 'Terms',
      content: '<div>Pay within <em>7 days</em></div>',
      format: 'html',
    },
  })

  assert.equal(data.notes?.format, 'text')
  assert.equal(data.notes?.content, 'Hello team\nThanks')
  assert.equal(data.terms?.format, 'text')
  assert.equal(data.terms?.content, 'Pay within 7 days')
})
