import test from 'node:test'
import assert from 'node:assert/strict'
import React from 'react'
import { pdf } from '@react-pdf/renderer'

import { PdfRenderer } from '../../components/pdf-new/renderers/PdfRenderer.tsx'
import Nexus from '../../components/pdf-new/templates/Nexus.tsx'

function createPdfModel(kind) {
  return {
    identity: {
      id: `${kind}-1`,
      kind,
      number: kind === 'invoice' ? 'INV-001' : 'QUO-001',
      title: kind === 'invoice' ? 'Invoice' : 'Quotation',
      issueDate: '2026-04-16',
      dueDate: kind === 'invoice' ? '2026-04-30' : undefined,
      validUntil: kind === 'quotation' ? '2026-04-30' : undefined,
      currency: 'NGN',
    },
    issuer: {
      label: 'From',
      name: 'Bigdrops Energy',
      addressLines: ['12 Power Lane', 'Lagos'],
      phone: '+2348000000000',
      email: 'hello@bigdrops.test',
    },
    recipient: {
      label: kind === 'invoice' ? 'Bill To' : 'Prepared For',
      name: 'Acme Client',
      addressLines: ['24 Client Road', 'Abuja'],
      phone: '+2348111111111',
      email: 'client@example.com',
    },
    headerFields: [
      { label: kind === 'invoice' ? 'Due Date' : 'Valid Until', value: '2026-04-30' },
    ],
    columns: [
      { key: 'description', label: 'Description', kind: 'builtin', align: 'left' },
      { key: 'quantity', label: 'Qty', kind: 'builtin', align: 'center' },
      { key: 'unit_price', label: 'Unit Price', kind: 'builtin', align: 'right' },
      { key: 'amount', label: 'Amount', kind: 'builtin', align: 'right' },
    ],
    items: [
      {
        id: `${kind}-item-1`,
        rowType: 'line',
        description: 'Solar panel installation',
        subDescription: 'Roof-mounted system',
        quantity: 2,
        unit: 'pcs',
        unitPrice: 150000,
        amount: 300000,
      },
    ],
    totals: {
      mode: 'standard',
      rows: [
        { key: 'subtotal', label: 'Subtotal', amount: 300000 },
        { key: 'total', label: 'Total', amount: 300000, emphasis: true },
      ],
      amountInWords: 'Three hundred thousand naira only',
    },
    notes: {
      title: 'Notes',
      content: 'Thanks for your business.',
      format: 'text',
    },
    terms: {
      title: 'Terms',
      content: 'Payment due within 14 days.',
      format: 'text',
    },
    signature: {
      name: 'Jane Doe',
      role: 'Operations Lead',
    },
    footerText: 'Generated by Bigdrops',
    metaFooter: {
      companyName: 'Bigdrops Energy',
    },
    logo: null,
    template: null,
  }
}

async function renderModel(model) {
  const blob = await pdf(
    React.createElement(PdfRenderer, {
      data: model,
      Template: Nexus,
    }),
  ).toBlob()

  assert.ok(blob instanceof Blob)
  assert.ok(blob.size > 0)
}

test('PdfRenderer renders the Nexus invoice template without crashing', async () => {
  await renderModel(createPdfModel('invoice'))
})

test('PdfRenderer renders the Nexus quotation template without crashing', async () => {
  await renderModel(createPdfModel('quotation'))
})
