import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
  page: {
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
    paddingBottom: 44,
  },
  headerBanner: {
    paddingTop: 26,
    paddingRight: 28,
    paddingBottom: 20,
    paddingLeft: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    position: 'relative',
  },
  headerBannerBottomLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  headerLeft: {
    flexDirection: 'column',
    maxWidth: 220,
  },
  logoImage: {
    width: 48,
    height: 48,
    marginBottom: 8,
  },
  logoPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  logoText: {
    fontSize: 9,
    fontWeight: 'bold',
    letterSpacing: 0.8,
  },
  companyName: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    marginBottom: 3,
  },
  companyContact: {
    fontSize: 7,
    lineHeight: 1.45,
    color: 'rgba(255,255,255,0.84)',
  },
  headerRight: {
    width: 205,
    alignItems: 'flex-end',
  },
  documentLabel: {
    fontSize: 7,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    color: 'rgba(255,255,255,0.84)',
    marginBottom: 4,
    textAlign: 'right',
  },
  documentTitle: {
    fontSize: 31,
    lineHeight: 1,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    textAlign: 'right',
  },
  metaStack: {
    marginTop: 10,
    width: '100%',
  },
  metaLine: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  metaLineGap: {
    marginTop: 2,
  },
  metaLabel: {
    fontSize: 7,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: 'rgba(255,255,255,0.74)',
    marginRight: 8,
  },
  metaValue: {
    fontSize: 7,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'right',
  },
  addressRow: {
    flexDirection: 'row',
    borderBottom: '1px solid #e2e8f0',
  },
  addressColumn: {
    flex: 1,
    paddingVertical: 17,
    paddingHorizontal: 28,
    borderRight: '1px solid #e2e8f0',
  },
  addressColumnLast: {
    flex: 1,
    paddingVertical: 17,
    paddingHorizontal: 28,
  },
  addressLabel: {
    fontSize: 6,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    marginBottom: 4,
  },
  addressName: {
    fontSize: 10,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  addressDetail: {
    fontSize: 8,
    lineHeight: 1.4,
  },
  customStrip: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderBottom: '1px solid #e2e8f0',
  },
  customFieldItem: {
    marginRight: 26,
    marginBottom: 4,
  },
  customFieldKey: {
    fontSize: 6,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    marginBottom: 2,
  },
  customFieldValue: {
    fontSize: 8,
    fontWeight: 'bold',
  },
  tableSection: {
    paddingHorizontal: 28,
    paddingTop: 14,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottom: '2px solid #0f172a',
    paddingBottom: 6,
    marginBottom: 2,
  },
  tableHeaderCell: {
    fontSize: 6.2,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: '#64748b',
  },
  colNum: {
    width: 18,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1px solid #e2e8f0',
    paddingTop: 8,
    paddingBottom: 8,
    alignItems: 'flex-start',
  },
  groupItemRow: {
    backgroundColor: '#f9fafb',
  },
  tableCellBase: {
    fontSize: 8,
    paddingRight: 4,
  },
  tableCellText: {
    fontSize: 8,
  },
  alignRight: {
    textAlign: 'right',
  },
  alignCenter: {
    textAlign: 'center',
  },
  itemTitle: {
    fontSize: 8,
    fontWeight: 'bold',
    lineHeight: 1.24,
    marginBottom: 2,
  },
  itemSub: {
    fontSize: 7,
    lineHeight: 1.35,
  },
  groupDescriptionCell: {
    paddingLeft: 12,
    position: 'relative',
  },
  groupItemPrefix: {
    position: 'absolute',
    left: 0,
    top: 0,
    fontSize: 8,
    fontWeight: 'bold',
  },
  makeCell: {
    fontSize: 7.3,
  },
  modelCell: {
    fontSize: 7,
    fontFamily: 'Courier',
  },
  qtyCell: {
    fontSize: 8,
  },
  priceCell: {
    fontSize: 8,
  },
  amountCell: {
    fontSize: 8,
    fontWeight: 'bold',
  },
  thumbnailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  thumbnailImg: {
    width: 54,
    height: 38,
    borderRadius: 4,
    border: '1px solid #cbd5e1',
    backgroundColor: '#f8fafc',
    marginRight: 8,
  },
  openImageLink: {
    fontSize: 6.5,
    fontWeight: 'bold',
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
    textDecoration: 'none',
  },
  groupHeaderRow: {
    paddingVertical: 6,
    paddingHorizontal: 9,
    borderBottom: '1px solid #dbeafe',
    marginTop: 4,
  },
  groupHeaderText: {
    fontSize: 8,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  groupSubtotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTop: '1px solid #cbd5e1',
    borderBottom: '2px solid #0f172a',
    paddingVertical: 7,
  },
  groupSubtotalSpacer: {
    flex: 1,
  },
  groupSubtotalLabel: {
    fontSize: 8,
    fontWeight: 'bold',
    marginRight: 8,
  },
  groupSubtotalValue: {
    fontSize: 8,
    fontWeight: 'bold',
    textAlign: 'right',
    minWidth: 88,
  },
  bottomPanel: {
    flexDirection: 'row',
    paddingTop: 16,
    paddingRight: 28,
    paddingBottom: 10,
    paddingLeft: 28,
    borderTop: '1px solid #e2e8f0',
    marginTop: 10,
  },
  bottomColumn: {
    flex: 1,
    marginRight: 22,
  },
  bottomColumnLast: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 7,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    borderBottom: '2px solid #dbeafe',
    paddingBottom: 3,
    marginBottom: 6,
  },
  sectionTitleGap: {
    marginTop: 10,
  },
  bankLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  bankLabel: {
    fontSize: 8,
  },
  bankValue: {
    fontSize: 8,
    fontWeight: 'bold',
  },
  textBlock: {
    fontSize: 7.4,
    lineHeight: 1.5,
  },
  attachmentLink: {
    fontSize: 8,
    fontWeight: 'bold',
    textDecoration: 'none',
    marginBottom: 4,
  },
  totalsSignatureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 6,
    marginHorizontal: 28,
    paddingTop: 12,
    paddingBottom: 10,
    borderTop: '2px solid #0f172a',
  },
  leftSection: {
    flex: 1,
    paddingRight: 18,
  },
  rightSection: {
    width: 178,
    alignItems: 'flex-end',
  },
  totalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    maxWidth: 330,
  },
  totalsLabel: {
    fontSize: 8.5,
    width: '50%',
  },
  totalsValue: {
    fontSize: 8.5,
    textAlign: 'right',
    width: '50%',
  },
  totalsGrandLabel: {
    fontSize: 10,
    fontWeight: 'bold',
    borderTop: '1px solid #cbd5e1',
    paddingTop: 6,
    marginTop: 2,
    width: '50%',
  },
  totalsGrandValue: {
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'right',
    borderTop: '1px solid #cbd5e1',
    paddingTop: 6,
    marginTop: 2,
    width: '50%',
  },
  amountWords: {
    fontSize: 7,
    fontStyle: 'italic',
    textAlign: 'right',
    marginTop: 2,
    width: '100%',
  },
  balanceDueLabel: {
    fontSize: 8.5,
    marginTop: 4,
    width: '50%',
  },
  balanceDueValue: {
    fontSize: 8.5,
    textAlign: 'right',
    marginTop: 4,
    width: '50%',
  },
  advanceBlock: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'stretch',
    borderLeftWidth: 4,
    borderLeftColor: '#1a56db',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  advanceColumn: {
    flex: 1,
  },
  advanceLabel: {
    fontSize: 6.4,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  advanceValue: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  advanceDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginHorizontal: 14,
  },
  extraFieldsVertical: {
    width: '100%',
    marginBottom: 16,
  },
  extraFieldItem: {
    width: '100%',
    marginBottom: 8,
    alignItems: 'flex-end',
  },
  extraFieldKey: {
    fontSize: 6,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    marginBottom: 1,
  },
  extraFieldValue: {
    fontSize: 8,
    fontWeight: 'bold',
    textAlign: 'right',
  },
  signatureBox: {
    width: '100%',
    alignItems: 'flex-end',
  },
  signatureImage: {
    width: 130,
    height: 40,
    marginBottom: 4,
  },
  signatureScribble: {
    fontFamily: 'Times-Italic',
    fontSize: 20,
    minWidth: 120,
    textAlign: 'right',
    borderBottom: '1px solid #cbd5e1',
    paddingBottom: 4,
    marginBottom: 4,
  },
  signatureName: {
    fontSize: 9,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  signatureRole: {
    fontSize: 7.4,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingVertical: 8,
    borderTop: '1px solid #cbd5e1',
  },
  footerLeft: {
    fontSize: 7,
    fontWeight: 'bold',
  },
  footerCenter: {
    fontSize: 7,
    color: '#64748b',
  },
  footerRight: {
    fontSize: 7,
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
})
