import { StyleSheet } from '@react-pdf/renderer';

export const palette = {
  paper: '#FBF7EF',
  canvas: '#201D18',
  night: '#17191F',
  night2: '#242832',
  bronze: '#B98248',
  bronzeSoft: '#EAD3B7',
  clay: '#DFB98B',
  sage: '#D8DED0',
  blueGrey: '#D9E1E6',
  ink: '#15171C',
  text: '#30343B',
  muted: '#69717F',
  faint: '#A3AAB5',
  line: '#D7CABA',
  softLine: '#E7DDCF',
  white: '#FFFFFF',
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 30,
    paddingHorizontal: 30,
    paddingBottom: 64,
    backgroundColor: '#FBF7EF',
    fontFamily: 'Helvetica',
    color: '#15171C',
    fontSize: 9.5,
    lineHeight: 1.35,
  },

  masthead: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  heroCard: {
    flex: 1.12,
    minHeight: 152,
    backgroundColor: '#17191F',
    borderRadius: 24,
    padding: 20,
    marginRight: 12,
    justifyContent: 'space-between',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoMark: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#B98248',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  logoMarkText: {
    color: '#17191F',
    fontSize: 15,
    fontWeight: 700,
  },
  logoImage: {
    width: 38,
    height: 38,
    borderRadius: 14,
    objectFit: 'cover',
    marginRight: 10,
  },
  brandName: {
    color: '#FFFFFF',
    fontSize: 12.5,
    fontWeight: 700,
  },
  brandMeta: {
    color: '#BFC3CA',
    fontSize: 8.7,
    marginTop: 2,
  },
  docKicker: {
    color: '#DFB98B',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: 700,
    marginBottom: 6,
  },
  docTitle: {
    color: '#FFFFFF',
    fontSize: 38,
    lineHeight: 0.95,
    fontWeight: 700,
    letterSpacing: -2.1,
  },
  secondaryLabel: {
    alignSelf: 'flex-start',
    marginTop: 9,
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#4A4E58',
    color: '#FFFFFF',
    backgroundColor: '#242832',
    fontSize: 7.5,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: 700,
  },

  metaPanel: {
    flex: 0.88,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  metaTile: {
    width: '48%',
    minHeight: 70,
    borderRadius: 17,
    padding: 11,
    marginLeft: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#D7CABA',
    justifyContent: 'space-between',
  },
  metaTileBronze: { backgroundColor: '#EAD3B7' },
  metaTileSage: { backgroundColor: '#D8DED0' },
  metaTileBlue: { backgroundColor: '#D9E1E6' },
  metaTilePaper: { backgroundColor: '#FFFFFF' },
  metaLabel: {
    color: '#69717F',
    fontSize: 7.6,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: 700,
  },
  metaValue: {
    color: '#15171C',
    fontSize: 11.3,
    fontWeight: 700,
  },

  parties: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  partyCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D7CABA',
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  partyCardLeft: { marginRight: 7 },
  partyCardRight: { marginLeft: 7 },
  partyHead: {
    backgroundColor: '#17191F',
    color: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 7.8,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    fontWeight: 700,
  },
  partyBody: {
    padding: 12,
  },
  partyName: {
    color: '#15171C',
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 5,
  },
  partyLine: {
    color: '#69717F',
    fontSize: 8.8,
    marginBottom: 2,
  },
  customInfoLine: {
    color: '#30343B',
    fontSize: 8.5,
    marginTop: 2,
  },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sectionTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionPill: {
    width: 24,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#B98248',
    marginRight: 7,
  },
  sectionTitle: {
    color: '#17191F',
    fontSize: 10,
    fontWeight: 700,
  },
  sectionCaption: {
    color: '#69717F',
    fontSize: 8.4,
  },

  tableFrame: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#D7CABA',
    overflow: 'hidden',
    marginBottom: 14,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#17191F',
  },
  tableHeaderCell: {
    color: '#C9CCD2',
    paddingVertical: 9,
    paddingHorizontal: 8,
    fontSize: 7.3,
    textTransform: 'uppercase',
    letterSpacing: 0.65,
    fontWeight: 700,
    borderRightWidth: 1,
    borderRightColor: '#343946',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E7DDCF',
    minHeight: 34,
    backgroundColor: '#FFFDF8',
  },
  tableRowAlt: {
    backgroundColor: '#F4E8D9',
  },
  tableCell: {
    paddingVertical: 9,
    paddingHorizontal: 8,
    color: '#30343B',
    fontSize: 8.6,
  },
  nestedCell: {
    borderLeftWidth: 3,
    borderLeftColor: '#B98248',
  },
  descriptionCellContent: {
    flexDirection: 'row',
  },
  itemImage: {
    width: 28,
    height: 28,
    borderRadius: 8,
    marginRight: 7,
    objectFit: 'cover',
  },
  itemTitle: {
    color: '#15171C',
    fontSize: 8.9,
    fontWeight: 700,
    marginBottom: 2,
  },
  itemDetail: {
    color: '#69717F',
    fontSize: 8.1,
  },
  groupHeaderRow: {
    backgroundColor: '#EAD3B7',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#D7CABA',
  },
  groupHeaderText: {
    color: '#17191F',
    fontSize: 8.7,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  groupFooterRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    backgroundColor: '#D8DED0',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#D7CABA',
  },
  groupFooterLabel: {
    color: '#30343B',
    fontSize: 8.7,
    fontWeight: 700,
    marginRight: 12,
  },
  groupFooterValue: {
    color: '#15171C',
    fontSize: 8.7,
    fontWeight: 700,
  },

  bottomArea: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  detailGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginRight: 12,
  },
  detailCard: {
    width: '48%',
    minHeight: 72,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#D7CABA',
    padding: 11,
    marginRight: 6,
    marginBottom: 8,
  },
  detailCardWide: {
    width: '98%',
  },
  bankCard: { backgroundColor: '#D9E1E6' },
  notesCard: { backgroundColor: '#FFFFFF' },
  termsCard: { backgroundColor: '#D8DED0' },
  attachmentsCard: { backgroundColor: '#EAD3B7' },
  detailTitle: {
    color: '#17191F',
    fontSize: 7.8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontWeight: 700,
    marginBottom: 6,
  },
  detailText: {
    color: '#30343B',
    fontSize: 8.3,
    marginBottom: 2,
  },
  attachmentWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  attachmentPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#D7CABA',
    backgroundColor: '#FFFFFF',
    paddingVertical: 5,
    paddingHorizontal: 7,
    marginRight: 5,
    marginBottom: 5,
    color: '#30343B',
    fontSize: 8,
    textDecoration: 'none',
  },

  summaryPanel: {
    width: 214,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#17191F',
    overflow: 'hidden',
  },
  summaryTop: {
    backgroundColor: '#17191F',
    padding: 13,
  },
  summaryKicker: {
    color: '#DFB98B',
    fontSize: 7.7,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    fontWeight: 700,
    marginBottom: 7,
  },
  summaryMainRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  summaryMainLabel: {
    color: '#D8DBE0',
    fontSize: 8.8,
  },
  summaryMainValue: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: 700,
  },
  summaryLines: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 13,
    paddingTop: 9,
    paddingBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E7DDCF',
    paddingVertical: 6,
  },
  summaryRowLabel: {
    color: '#69717F',
    fontSize: 8.5,
  },
  summaryRowValue: {
    color: '#15171C',
    fontSize: 8.7,
    fontWeight: 700,
  },
  balanceDue: {
    marginTop: 8,
    borderRadius: 12,
    backgroundColor: '#EAD3B7',
    padding: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  balanceDueLabel: {
    color: '#17191F',
    fontSize: 8.7,
    fontWeight: 700,
  },
  balanceDueValue: {
    color: '#17191F',
    fontSize: 8.7,
    fontWeight: 700,
  },
  amountWords: {
    color: '#69717F',
    fontSize: 8.1,
    marginTop: 8,
    lineHeight: 1.35,
  },
  advanceBlock: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#E7DDCF',
    paddingTop: 7,
  },
  advanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  advanceLabel: {
    color: '#69717F',
    fontSize: 8.3,
  },
  advanceValue: {
    color: '#15171C',
    fontSize: 8.6,
    fontWeight: 700,
  },

  signatureBand: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  signatureCopy: {
    flex: 1,
    color: '#69717F',
    fontSize: 8.3,
    marginRight: 12,
  },
  signatureBox: {
    width: 180,
    minHeight: 70,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#D7CABA',
    backgroundColor: '#FFFFFF',
    padding: 10,
    justifyContent: 'flex-end',
  },
  signatureImage: {
    width: 120,
    height: 34,
    objectFit: 'contain',
    marginBottom: 5,
  },
  signatureLine: {
    borderTopWidth: 1,
    borderTopColor: '#17191F',
    paddingTop: 5,
  },
  signatureName: {
    color: '#15171C',
    fontSize: 8.6,
    fontWeight: 700,
  },
  signatureRole: {
    color: '#69717F',
    fontSize: 7.8,
    marginTop: 1,
  },

  footer: {
    position: 'absolute',
    left: 30,
    right: 30,
    bottom: 24,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#D7CABA',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#69717F',
    fontSize: 7.8,
  },
  footerLeft: {
    flex: 1,
    paddingRight: 10,
  },
  footerRight: {
    width: 90,
    textAlign: 'right',
  },
});

export function resolveAlignment(align?: string) {
  if (align === 'right') return { textAlign: 'right' as const };
  if (align === 'center') return { textAlign: 'center' as const };
  return { textAlign: 'left' as const };
}
